### ISSUE TITLE
Do Zero a Herói Front-End (Parte I)

### ISSUE THREAD

**Issue by vdms** [LFeh/lfeh.github.io#12]
http://www.felipefialho.com/blog/2016/do-zero-a-heroi-do-front-end-parte-1

Trocar "Me lembro (...)" para Lembro-me (...).

Não é erro de tradução em si, mas de português.

Referências:
http://blog.tribunadonorte.com.br/gramaticando/675 
http://educacao.uol.com.br/dicas-portugues/pronome-atono-no-inicio-da-frase-sim-ou-nao.jhtm
http://dicasdiariasdeportugues.com.br/nao-inicie-frase-com-pronome-obliquo/

**Comment by LFeh** [comment]
Valeu @vdms ;)
