### ISSUE TITLE
HTTPS on Github Pages 

### ISSUE THREAD

**Issue by LFeh** [LFeh/lfeh.github.io#14]
https://willianjusten.com.br/https-no-github-pages-com-custom-domain/

@willianjusten

**Comment by LFeh** [comment]
hahahaha, to ligado. Te citei porque vou seguir seu artigo =p

**Comment by willianjusten** [comment]
Ahhh sim xD

**Comment by fititnt** [comment]
Um dia eu crio vergonha na cara e também faço isso nas dezenas de gh-pages que tenho acesso #teamCasaDeFerreiroEspetoDePau
