### ISSUE TITLE
Do Zero a Herói Front-End (Parte II) - Link errado

### ISSUE THREAD

**Issue by ifdiego** [LFeh/lfeh.github.io#21]
Opa, 

http://www.felipefialho.com/blog/2016/do-zero-a-heroi-do-front-end-parte-2

Logo no início do texto, na parte de "o básico do javascript" há 4 links para o MDN.
Acontece que o último link, sobre functions, está levando para a página de loops and iterations.

Acredito que o link correto seja esse, certo?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

**Comment by LFeh** [comment]
Thanks @ifdiego :)
