### ISSUE TITLE
[Bug] Título escondido pelo header

### ISSUE THREAD

**Issue by vinicaval** [LFeh/lfeh.github.io#22]
Olá Felipe,

Encontrei um bug vendo seu post numa resolução de 1366x768, no Chrome.(não testei em outros browsers mas imagino que seja um problema da mediaquery dessa resolução)

![image](https://cloud.githubusercontent.com/assets/1177749/18916592/47a8eec0-856b-11e6-9089-647b645052ca.png)

Em resoluções maiores, esse problema não acontece.

Att.

**Comment by LFeh** [comment]
Valeu!

Xa eu arrumar aqui \o

**Comment by LFeh** [comment]
@vinicaval O efeito era bonitinho mas estava atrapalhando a usabilidade. Da uma olhada agora ;)
